---
- name: configure nginx in the test server.
  hosts: test
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
    - name: start service
      service:
        name: nginx
        status: started    